# Generated by Django 5.0.3 on 2024-03-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fam',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
